CREATE TABLE IF NOT EXISTS app_settings (
  key text PRIMARY KEY,
  value text NOT NULL
);

CREATE TABLE IF NOT EXISTS customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  company text,
  tax_number text,
  phone text,
  email text,
  address text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS repair_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  label_key text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS repairs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repair_number text NOT NULL UNIQUE,
  customer_id bigint NOT NULL REFERENCES customers(id),
  status_id bigint NOT NULL REFERENCES repair_statuses(id),
  device_type text,
  brand text,
  model text,
  serial_number text,
  imei text,
  reported_fault text,
  accessories text,
  general_condition text,
  diagnosis text,
  work_performed text,
  estimated_value double precision,
  final_value double precision,
  internal_notes text,
  opened_at timestamptz NOT NULL DEFAULT now(),
  closed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS repair_status_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repair_id bigint NOT NULL REFERENCES repairs(id) ON DELETE CASCADE,
  status_id bigint NOT NULL REFERENCES repair_statuses(id),
  changed_at timestamptz NOT NULL DEFAULT now(),
  note text
);

CREATE INDEX IF NOT EXISTS repairs_customer_id_idx ON repairs(customer_id);
CREATE INDEX IF NOT EXISTS repairs_status_id_idx ON repairs(status_id);
CREATE INDEX IF NOT EXISTS repair_status_history_repair_id_idx ON repair_status_history(repair_id);

INSERT INTO repair_statuses (code, label_key, sort_order) VALUES
  ('RECEIVED', 'status.received', 10),
  ('DIAGNOSIS', 'status.diagnosis', 20),
  ('WAITING_CUSTOMER', 'status.waitingCustomer', 30),
  ('WAITING_PARTS', 'status.waitingParts', 40),
  ('IN_REPAIR', 'status.inRepair', 50),
  ('REPAIRED', 'status.repaired', 60),
  ('READY', 'status.ready', 70),
  ('DELIVERED', 'status.delivered', 80),
  ('CANCELLED', 'status.cancelled', 90)
ON CONFLICT (code) DO NOTHING;
